Kdm\CmfBundle\Doctrine\Phpcr\Page:
    fields:
        internal:
            type: boolean
        createdAt:
            type: date
        updatedAt:
            type: date
    child:
        seoMetadata: ~
    lifecycleCallbacks:
        prePersist: [ onPrePersist ]
        preUpdate: [ onPreUpdate ]
