Kdm\CmfBundle\Doctrine\Phpcr\Page:
    fields:
        i18nName:
            type: string
            translated: true
            nullable: true
        internal:
            type: boolean
        createdAt:
            type: date
        updatedAt:
            type: date
    child:
        seoMetadata: ~
    referrers:
        routes:
            referringDocument: 'Kdm\CmfBundle\Doctrine\Phpcr\Route'
            referencedBy: content
            cascade: [ persist, remove ]
    lifecycleCallbacks:
        prePersist: [ onPrePersist ]
        preUpdate: [ onPreUpdate ]
